[project]
name = "pyinterval"
version = "0.1.0"
description = "A library for defining and working with relative dates and intervals of time."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dateutil == 2.9.0",
]
